# Generated by Django 4.2.6 on 2023-10-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='picture',
            field=models.ImageField(default='settings.MEDIA_ROOT/images/default.jpeg', upload_to='images/'),
        ),
    ]
